[project]
name = "smart-greenhouse-backend"
version = "0.1.0"
description = "Smart Greenhouse Backend"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "psycopg[binary]",
    "alembic",
    "pydantic-settings",
    "scalar-fastapi",
    "pytest",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]