"""device_family

Revision ID: 75f75cc3e096
Revises: ebfa3e42b772
Create Date: 2026-09-20 11:11:44.802733

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



revision: str = '75f75cc3e096'
down_revision: Union[str, Sequence[str], None] = 'ebfa3e42b772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_family', sa.String(length=32), server_default=sa.text("'simulation'"), nullable=False))
    op.create_index('ix_devices_family', 'devices', ['device_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_family', table_name='devices')
    op.drop_column('devices', 'device_family')
    # ### end Alembic commands ###