"""add locations and zones

Revision ID: 9f66efb206af
Revises: 75f75cc3e096
Create Date: 2026-09-20 14:48:41.748765

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

revision: str = '9f66efb206af'
down_revision: Union[str, Sequence[str], None] = '75f75cc3e096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('moisture_threshold_low', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('moisture_threshold_high', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_zones_location_id', 'zones', ['location_id'], unique=False)
    op.add_column('devices', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_index('ix_devices_location_id', 'devices', ['location_id'], unique=False)
    op.create_foreign_key(
    'fk_devices_location_id',
    'devices',
    'locations',
    ['location_id'],
    ['id'],
    ondelete='SET NULL',
)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    'fk_devices_location_id',
    'devices',
    type_='foreignkey',
)
    op.drop_index('ix_devices_location_id', table_name='devices')
    op.drop_column('devices', 'location_id')
    op.drop_index('ix_zones_location_id', table_name='zones')
    op.drop_table('zones')
    op.drop_table('locations')
    # ### end Alembic commands ###