"""devices

Revision ID: ebfa3e42b772
Revises: 001_baseline
Create Date: 2026-09-15 13:21:24.221907

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

revision: str = 'ebfa3e42b772'
down_revision: Union[str, Sequence[str], None] = '001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), server_default=sa.text("'sensor'"), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_devices_role', 'devices', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_role', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###